---@class UnityEngine.UI.InputField : UnityEngine.UI.Selectable
---@field shouldHideMobileInput bool
---@field text string
---@field isFocused bool
---@field caretBlinkRate float
---@field caretWidth int
---@field textComponent UnityEngine.UI.Text
---@field placeholder UnityEngine.UI.Graphic
---@field caretColor UnityEngine.Color
---@field customCaretColor bool
---@field selectionColor UnityEngine.Color
---@field onEndEdit UnityEngine.UI.InputField.SubmitEvent
---@field onValueChanged UnityEngine.UI.InputField.OnChangeEvent
---@field onValidateInput UnityEngine.UI.InputField.OnValidateInput
---@field characterLimit int
---@field contentType UnityEngine.UI.InputField.ContentType
---@field lineType UnityEngine.UI.InputField.LineType
---@field inputType UnityEngine.UI.InputField.InputType
---@field keyboardType UnityEngine.TouchScreenKeyboardType
---@field characterValidation UnityEngine.UI.InputField.CharacterValidation
---@field readOnly bool
---@field multiLine bool
---@field asteriskChar char
---@field wasCanceled bool
---@field caretPosition int
---@field selectionAnchorPosition int
---@field selectionFocusPosition int
---@field minWidth float
---@field preferredWidth float
---@field flexibleWidth float
---@field minHeight float
---@field preferredHeight float
---@field flexibleHeight float
---@field layoutPriority int
local m = {}
---@param shift bool
function m:MoveTextEnd(shift) end
---@param shift bool
function m:MoveTextStart(shift) end
---@param eventData UnityEngine.EventSystems.PointerEventData
function m:OnBeginDrag(eventData) end
---@param eventData UnityEngine.EventSystems.PointerEventData
function m:OnDrag(eventData) end
---@param eventData UnityEngine.EventSystems.PointerEventData
function m:OnEndDrag(eventData) end
---@param eventData UnityEngine.EventSystems.PointerEventData
function m:OnPointerDown(eventData) end
---@param e UnityEngine.Event
function m:ProcessEvent(e) end
---@param eventData UnityEngine.EventSystems.BaseEventData
function m:OnUpdateSelected(eventData) end
function m:ForceLabelUpdate() end
---@param update UnityEngine.UI.CanvasUpdate
function m:Rebuild(update) end
function m:LayoutComplete() end
function m:GraphicUpdateComplete() end
function m:ActivateInputField() end
---@param eventData UnityEngine.EventSystems.BaseEventData
function m:OnSelect(eventData) end
---@param eventData UnityEngine.EventSystems.PointerEventData
function m:OnPointerClick(eventData) end
function m:DeactivateInputField() end
---@param eventData UnityEngine.EventSystems.BaseEventData
function m:OnDeselect(eventData) end
---@param eventData UnityEngine.EventSystems.BaseEventData
function m:OnSubmit(eventData) end
function m:CalculateLayoutInputHorizontal() end
function m:CalculateLayoutInputVertical() end
UnityEngine = {}
UnityEngine.UI = {}
UnityEngine.UI.InputField = m
return m