//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DG_Tweening_TweenParamsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DG.Tweening.TweenParams), typeof(System.Object));
		L.RegFunction("Clear", Clear);
		L.RegFunction("SetAutoKill", SetAutoKill);
		L.RegFunction("SetId", SetId);
		L.RegFunction("SetTarget", SetTarget);
		L.RegFunction("SetLoops", SetLoops);
		L.RegFunction("SetEase", SetEase);
		L.RegFunction("SetRecyclable", SetRecyclable);
		L.RegFunction("SetUpdate", SetUpdate);
		L.RegFunction("OnStart", OnStart);
		L.RegFunction("OnPlay", OnPlay);
		L.RegFunction("OnRewind", OnRewind);
		L.RegFunction("OnUpdate", OnUpdate);
		L.RegFunction("OnStepComplete", OnStepComplete);
		L.RegFunction("OnComplete", OnComplete);
		L.RegFunction("OnKill", OnKill);
		L.RegFunction("OnWaypointChange", OnWaypointChange);
		L.RegFunction("SetDelay", SetDelay);
		L.RegFunction("SetRelative", SetRelative);
		L.RegFunction("SetSpeedBased", SetSpeedBased);
		L.RegFunction("New", _CreateDG_Tweening_TweenParams);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Params", get_Params, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateDG_Tweening_TweenParams(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				DG.Tweening.TweenParams obj = new DG.Tweening.TweenParams();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: DG.Tweening.TweenParams.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
			DG.Tweening.TweenParams o = obj.Clear();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAutoKill(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
				DG.Tweening.TweenParams o = obj.SetAutoKill();
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2)
			{
				DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
				bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
				DG.Tweening.TweenParams o = obj.SetAutoKill(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: DG.Tweening.TweenParams.SetAutoKill");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetId(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
			object arg0 = ToLua.ToVarObject(L, 2);
			DG.Tweening.TweenParams o = obj.SetId(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetTarget(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
			object arg0 = ToLua.ToVarObject(L, 2);
			DG.Tweening.TweenParams o = obj.SetTarget(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetLoops(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
				int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
				DG.Tweening.TweenParams o = obj.SetLoops(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 3)
			{
				DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
				int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
				System.Nullable<DG.Tweening.LoopType> arg1 = ToLua.CheckNullable<DG.Tweening.LoopType>(L, 3);
				DG.Tweening.TweenParams o = obj.SetLoops(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: DG.Tweening.TweenParams.SetLoops");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetEase(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<DG.Tweening.Ease>(L, 2))
			{
				DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
				DG.Tweening.Ease arg0 = (DG.Tweening.Ease)ToLua.ToObject(L, 2);
				DG.Tweening.TweenParams o = obj.SetEase(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<UnityEngine.AnimationCurve>(L, 2))
			{
				DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
				UnityEngine.AnimationCurve arg0 = (UnityEngine.AnimationCurve)ToLua.ToObject(L, 2);
				DG.Tweening.TweenParams o = obj.SetEase(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<DG.Tweening.EaseFunction>(L, 2))
			{
				DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
				DG.Tweening.EaseFunction arg0 = (DG.Tweening.EaseFunction)ToLua.ToObject(L, 2);
				DG.Tweening.TweenParams o = obj.SetEase(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 3)
			{
				DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
				DG.Tweening.Ease arg0 = (DG.Tweening.Ease)ToLua.CheckObject(L, 2, typeof(DG.Tweening.Ease));
				System.Nullable<float> arg1 = ToLua.CheckNullable<float>(L, 3);
				DG.Tweening.TweenParams o = obj.SetEase(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 4)
			{
				DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
				DG.Tweening.Ease arg0 = (DG.Tweening.Ease)ToLua.CheckObject(L, 2, typeof(DG.Tweening.Ease));
				System.Nullable<float> arg1 = ToLua.CheckNullable<float>(L, 3);
				System.Nullable<float> arg2 = ToLua.CheckNullable<float>(L, 4);
				DG.Tweening.TweenParams o = obj.SetEase(arg0, arg1, arg2);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: DG.Tweening.TweenParams.SetEase");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetRecyclable(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
				DG.Tweening.TweenParams o = obj.SetRecyclable();
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2)
			{
				DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
				bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
				DG.Tweening.TweenParams o = obj.SetRecyclable(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: DG.Tweening.TweenParams.SetRecyclable");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetUpdate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<bool>(L, 2))
			{
				DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
				bool arg0 = LuaDLL.lua_toboolean(L, 2);
				DG.Tweening.TweenParams o = obj.SetUpdate(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<DG.Tweening.UpdateType>(L, 2))
			{
				DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
				DG.Tweening.UpdateType arg0 = (DG.Tweening.UpdateType)ToLua.ToObject(L, 2);
				DG.Tweening.TweenParams o = obj.SetUpdate(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 3)
			{
				DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
				DG.Tweening.UpdateType arg0 = (DG.Tweening.UpdateType)ToLua.CheckObject(L, 2, typeof(DG.Tweening.UpdateType));
				bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
				DG.Tweening.TweenParams o = obj.SetUpdate(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: DG.Tweening.TweenParams.SetUpdate");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnStart(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
			DG.Tweening.TweenCallback arg0 = (DG.Tweening.TweenCallback)ToLua.CheckDelegate<DG.Tweening.TweenCallback>(L, 2);
			DG.Tweening.TweenParams o = obj.OnStart(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPlay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
			DG.Tweening.TweenCallback arg0 = (DG.Tweening.TweenCallback)ToLua.CheckDelegate<DG.Tweening.TweenCallback>(L, 2);
			DG.Tweening.TweenParams o = obj.OnPlay(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnRewind(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
			DG.Tweening.TweenCallback arg0 = (DG.Tweening.TweenCallback)ToLua.CheckDelegate<DG.Tweening.TweenCallback>(L, 2);
			DG.Tweening.TweenParams o = obj.OnRewind(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
			DG.Tweening.TweenCallback arg0 = (DG.Tweening.TweenCallback)ToLua.CheckDelegate<DG.Tweening.TweenCallback>(L, 2);
			DG.Tweening.TweenParams o = obj.OnUpdate(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnStepComplete(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
			DG.Tweening.TweenCallback arg0 = (DG.Tweening.TweenCallback)ToLua.CheckDelegate<DG.Tweening.TweenCallback>(L, 2);
			DG.Tweening.TweenParams o = obj.OnStepComplete(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnComplete(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
			DG.Tweening.TweenCallback arg0 = (DG.Tweening.TweenCallback)ToLua.CheckDelegate<DG.Tweening.TweenCallback>(L, 2);
			DG.Tweening.TweenParams o = obj.OnComplete(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnKill(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
			DG.Tweening.TweenCallback arg0 = (DG.Tweening.TweenCallback)ToLua.CheckDelegate<DG.Tweening.TweenCallback>(L, 2);
			DG.Tweening.TweenParams o = obj.OnKill(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnWaypointChange(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
			DG.Tweening.TweenCallback<int> arg0 = (DG.Tweening.TweenCallback<int>)ToLua.CheckDelegate<DG.Tweening.TweenCallback<int>>(L, 2);
			DG.Tweening.TweenParams o = obj.OnWaypointChange(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetDelay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			DG.Tweening.TweenParams o = obj.SetDelay(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetRelative(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
				DG.Tweening.TweenParams o = obj.SetRelative();
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2)
			{
				DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
				bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
				DG.Tweening.TweenParams o = obj.SetRelative(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: DG.Tweening.TweenParams.SetRelative");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSpeedBased(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
				DG.Tweening.TweenParams o = obj.SetSpeedBased();
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2)
			{
				DG.Tweening.TweenParams obj = (DG.Tweening.TweenParams)ToLua.CheckObject<DG.Tweening.TweenParams>(L, 1);
				bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
				DG.Tweening.TweenParams o = obj.SetSpeedBased(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: DG.Tweening.TweenParams.SetSpeedBased");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Params(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, DG.Tweening.TweenParams.Params);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

