//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DG_Tweening_EaseFactoryWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DG.Tweening.EaseFactory), typeof(System.Object));
		L.RegFunction("StopMotion", StopMotion);
		L.RegFunction("New", _CreateDG_Tweening_EaseFactory);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateDG_Tweening_EaseFactory(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				DG.Tweening.EaseFactory obj = new DG.Tweening.EaseFactory();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: DG.Tweening.EaseFactory.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopMotion(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
				DG.Tweening.EaseFunction o = DG.Tweening.EaseFactory.StopMotion(arg0);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<System.Nullable<DG.Tweening.Ease>>(L, 2))
			{
				int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
				System.Nullable<DG.Tweening.Ease> arg1 = ToLua.ToNullable<DG.Tweening.Ease>(L, 2);
				DG.Tweening.EaseFunction o = DG.Tweening.EaseFactory.StopMotion(arg0, arg1);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<UnityEngine.AnimationCurve>(L, 2))
			{
				int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.AnimationCurve arg1 = (UnityEngine.AnimationCurve)ToLua.ToObject(L, 2);
				DG.Tweening.EaseFunction o = DG.Tweening.EaseFactory.StopMotion(arg0, arg1);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<DG.Tweening.EaseFunction>(L, 2))
			{
				int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
				DG.Tweening.EaseFunction arg1 = (DG.Tweening.EaseFunction)ToLua.ToObject(L, 2);
				DG.Tweening.EaseFunction o = DG.Tweening.EaseFactory.StopMotion(arg0, arg1);
				ToLua.Push(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: DG.Tweening.EaseFactory.StopMotion");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

