//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DG_Tweening_DOTweenAnimationWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DG.Tweening.DOTweenAnimation), typeof(DG.Tweening.Core.ABSAnimationComponent));
		L.RegFunction("CreateTween", CreateTween);
		L.RegFunction("DOPlay", DOPlay);
		L.RegFunction("DOPlayBackwards", DOPlayBackwards);
		L.RegFunction("DOPlayForward", DOPlayForward);
		L.RegFunction("DOPause", DOPause);
		L.RegFunction("DOTogglePause", DOTogglePause);
		L.RegFunction("DORewind", DORewind);
		L.RegFunction("DORestart", DORestart);
		L.RegFunction("DOComplete", DOComplete);
		L.RegFunction("DOKill", DOKill);
		L.RegFunction("DOPlayById", DOPlayById);
		L.RegFunction("DOPlayAllById", DOPlayAllById);
		L.RegFunction("DOPauseAllById", DOPauseAllById);
		L.RegFunction("DOPlayBackwardsById", DOPlayBackwardsById);
		L.RegFunction("DOPlayBackwardsAllById", DOPlayBackwardsAllById);
		L.RegFunction("DOPlayForwardById", DOPlayForwardById);
		L.RegFunction("DOPlayForwardAllById", DOPlayForwardAllById);
		L.RegFunction("DOPlayNext", DOPlayNext);
		L.RegFunction("DORewindAndPlayNext", DORewindAndPlayNext);
		L.RegFunction("DORewindAllById", DORewindAllById);
		L.RegFunction("DORestartById", DORestartById);
		L.RegFunction("DORestartAllById", DORestartAllById);
		L.RegFunction("GetTweens", GetTweens);
		L.RegFunction("TypeToDOTargetType", TypeToDOTargetType);
		L.RegFunction("CreateEditorPreview", CreateEditorPreview);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("targetIsSelf", get_targetIsSelf, set_targetIsSelf);
		L.RegVar("targetGO", get_targetGO, set_targetGO);
		L.RegVar("tweenTargetIsTargetGO", get_tweenTargetIsTargetGO, set_tweenTargetIsTargetGO);
		L.RegVar("delay", get_delay, set_delay);
		L.RegVar("duration", get_duration, set_duration);
		L.RegVar("easeType", get_easeType, set_easeType);
		L.RegVar("easeCurve", get_easeCurve, set_easeCurve);
		L.RegVar("loopType", get_loopType, set_loopType);
		L.RegVar("loops", get_loops, set_loops);
		L.RegVar("id", get_id, set_id);
		L.RegVar("isRelative", get_isRelative, set_isRelative);
		L.RegVar("isFrom", get_isFrom, set_isFrom);
		L.RegVar("isIndependentUpdate", get_isIndependentUpdate, set_isIndependentUpdate);
		L.RegVar("autoKill", get_autoKill, set_autoKill);
		L.RegVar("isActive", get_isActive, set_isActive);
		L.RegVar("isValid", get_isValid, set_isValid);
		L.RegVar("target", get_target, set_target);
		L.RegVar("animationType", get_animationType, set_animationType);
		L.RegVar("targetType", get_targetType, set_targetType);
		L.RegVar("forcedTargetType", get_forcedTargetType, set_forcedTargetType);
		L.RegVar("autoPlay", get_autoPlay, set_autoPlay);
		L.RegVar("useTargetAsV3", get_useTargetAsV3, set_useTargetAsV3);
		L.RegVar("endValueFloat", get_endValueFloat, set_endValueFloat);
		L.RegVar("endValueV3", get_endValueV3, set_endValueV3);
		L.RegVar("endValueV2", get_endValueV2, set_endValueV2);
		L.RegVar("endValueColor", get_endValueColor, set_endValueColor);
		L.RegVar("endValueString", get_endValueString, set_endValueString);
		L.RegVar("endValueRect", get_endValueRect, set_endValueRect);
		L.RegVar("endValueTransform", get_endValueTransform, set_endValueTransform);
		L.RegVar("optionalBool0", get_optionalBool0, set_optionalBool0);
		L.RegVar("optionalFloat0", get_optionalFloat0, set_optionalFloat0);
		L.RegVar("optionalInt0", get_optionalInt0, set_optionalInt0);
		L.RegVar("optionalRotationMode", get_optionalRotationMode, set_optionalRotationMode);
		L.RegVar("optionalScrambleMode", get_optionalScrambleMode, set_optionalScrambleMode);
		L.RegVar("optionalString", get_optionalString, set_optionalString);
		L.RegVar("OnReset", get_OnReset, set_OnReset);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateTween(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			obj.CreateTween();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DOPlay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			obj.DOPlay();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DOPlayBackwards(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			obj.DOPlayBackwards();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DOPlayForward(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			obj.DOPlayForward();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DOPause(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			obj.DOPause();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DOTogglePause(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			obj.DOTogglePause();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DORewind(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			obj.DORewind();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DORestart(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
				obj.DORestart();
				return 0;
			}
			else if (count == 2)
			{
				DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
				bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
				obj.DORestart(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: DG.Tweening.DOTweenAnimation.DORestart");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DOComplete(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			obj.DOComplete();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DOKill(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			obj.DOKill();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DOPlayById(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.DOPlayById(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DOPlayAllById(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.DOPlayAllById(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DOPauseAllById(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.DOPauseAllById(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DOPlayBackwardsById(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.DOPlayBackwardsById(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DOPlayBackwardsAllById(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.DOPlayBackwardsAllById(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DOPlayForwardById(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.DOPlayForwardById(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DOPlayForwardAllById(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.DOPlayForwardAllById(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DOPlayNext(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			obj.DOPlayNext();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DORewindAndPlayNext(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			obj.DORewindAndPlayNext();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DORewindAllById(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.DORewindAllById(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DORestartById(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.DORestartById(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DORestartAllById(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.DORestartAllById(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTweens(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			System.Collections.Generic.List<DG.Tweening.Tween> o = obj.GetTweens();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int TypeToDOTargetType(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.Type arg0 = ToLua.CheckMonoType(L, 1);
			DG.Tweening.DOTweenAnimation.TargetType o = DG.Tweening.DOTweenAnimation.TypeToDOTargetType(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateEditorPreview(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)ToLua.CheckObject<DG.Tweening.DOTweenAnimation>(L, 1);
			DG.Tweening.Tween o = obj.CreateEditorPreview();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_targetIsSelf(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool ret = obj.targetIsSelf;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index targetIsSelf on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_targetGO(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			UnityEngine.GameObject ret = obj.targetGO;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index targetGO on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_tweenTargetIsTargetGO(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool ret = obj.tweenTargetIsTargetGO;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index tweenTargetIsTargetGO on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_delay(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			float ret = obj.delay;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index delay on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_duration(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			float ret = obj.duration;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index duration on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_easeType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			DG.Tweening.Ease ret = obj.easeType;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index easeType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_easeCurve(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			UnityEngine.AnimationCurve ret = obj.easeCurve;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index easeCurve on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_loopType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			DG.Tweening.LoopType ret = obj.loopType;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index loopType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_loops(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			int ret = obj.loops;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index loops on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_id(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			string ret = obj.id;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index id on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isRelative(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool ret = obj.isRelative;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index isRelative on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isFrom(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool ret = obj.isFrom;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index isFrom on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isIndependentUpdate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool ret = obj.isIndependentUpdate;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index isIndependentUpdate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_autoKill(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool ret = obj.autoKill;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index autoKill on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isActive(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool ret = obj.isActive;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index isActive on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isValid(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool ret = obj.isValid;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index isValid on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_target(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			UnityEngine.Component ret = obj.target;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index target on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_animationType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			DG.Tweening.DOTweenAnimation.AnimationType ret = obj.animationType;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index animationType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_targetType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			DG.Tweening.DOTweenAnimation.TargetType ret = obj.targetType;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index targetType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_forcedTargetType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			DG.Tweening.DOTweenAnimation.TargetType ret = obj.forcedTargetType;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index forcedTargetType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_autoPlay(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool ret = obj.autoPlay;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index autoPlay on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_useTargetAsV3(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool ret = obj.useTargetAsV3;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index useTargetAsV3 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_endValueFloat(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			float ret = obj.endValueFloat;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index endValueFloat on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_endValueV3(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			UnityEngine.Vector3 ret = obj.endValueV3;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index endValueV3 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_endValueV2(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			UnityEngine.Vector2 ret = obj.endValueV2;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index endValueV2 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_endValueColor(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			UnityEngine.Color ret = obj.endValueColor;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index endValueColor on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_endValueString(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			string ret = obj.endValueString;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index endValueString on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_endValueRect(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			UnityEngine.Rect ret = obj.endValueRect;
			ToLua.PushValue(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index endValueRect on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_endValueTransform(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			UnityEngine.Transform ret = obj.endValueTransform;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index endValueTransform on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_optionalBool0(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool ret = obj.optionalBool0;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index optionalBool0 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_optionalFloat0(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			float ret = obj.optionalFloat0;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index optionalFloat0 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_optionalInt0(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			int ret = obj.optionalInt0;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index optionalInt0 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_optionalRotationMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			DG.Tweening.RotateMode ret = obj.optionalRotationMode;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index optionalRotationMode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_optionalScrambleMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			DG.Tweening.ScrambleMode ret = obj.optionalScrambleMode;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index optionalScrambleMode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_optionalString(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			string ret = obj.optionalString;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index optionalString on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnReset(IntPtr L)
	{
		ToLua.Push(L, new EventObject(typeof(System.Action<DG.Tweening.DOTweenAnimation>)));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_targetIsSelf(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.targetIsSelf = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index targetIsSelf on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_targetGO(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.targetGO = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index targetGO on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_tweenTargetIsTargetGO(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.tweenTargetIsTargetGO = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index tweenTargetIsTargetGO on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_delay(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.delay = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index delay on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_duration(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.duration = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index duration on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_easeType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			DG.Tweening.Ease arg0 = (DG.Tweening.Ease)ToLua.CheckObject(L, 2, typeof(DG.Tweening.Ease));
			obj.easeType = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index easeType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_easeCurve(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			UnityEngine.AnimationCurve arg0 = (UnityEngine.AnimationCurve)ToLua.CheckObject<UnityEngine.AnimationCurve>(L, 2);
			obj.easeCurve = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index easeCurve on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_loopType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			DG.Tweening.LoopType arg0 = (DG.Tweening.LoopType)ToLua.CheckObject(L, 2, typeof(DG.Tweening.LoopType));
			obj.loopType = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index loopType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_loops(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.loops = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index loops on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_id(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.id = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index id on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_isRelative(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.isRelative = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index isRelative on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_isFrom(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.isFrom = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index isFrom on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_isIndependentUpdate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.isIndependentUpdate = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index isIndependentUpdate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_autoKill(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.autoKill = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index autoKill on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_isActive(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.isActive = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index isActive on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_isValid(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.isValid = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index isValid on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_target(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			UnityEngine.Component arg0 = (UnityEngine.Component)ToLua.CheckObject<UnityEngine.Component>(L, 2);
			obj.target = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index target on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_animationType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			DG.Tweening.DOTweenAnimation.AnimationType arg0 = (DG.Tweening.DOTweenAnimation.AnimationType)ToLua.CheckObject(L, 2, typeof(DG.Tweening.DOTweenAnimation.AnimationType));
			obj.animationType = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index animationType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_targetType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			DG.Tweening.DOTweenAnimation.TargetType arg0 = (DG.Tweening.DOTweenAnimation.TargetType)ToLua.CheckObject(L, 2, typeof(DG.Tweening.DOTweenAnimation.TargetType));
			obj.targetType = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index targetType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_forcedTargetType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			DG.Tweening.DOTweenAnimation.TargetType arg0 = (DG.Tweening.DOTweenAnimation.TargetType)ToLua.CheckObject(L, 2, typeof(DG.Tweening.DOTweenAnimation.TargetType));
			obj.forcedTargetType = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index forcedTargetType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_autoPlay(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.autoPlay = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index autoPlay on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_useTargetAsV3(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.useTargetAsV3 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index useTargetAsV3 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_endValueFloat(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.endValueFloat = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index endValueFloat on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_endValueV3(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
			obj.endValueV3 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index endValueV3 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_endValueV2(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			UnityEngine.Vector2 arg0 = ToLua.ToVector2(L, 2);
			obj.endValueV2 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index endValueV2 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_endValueColor(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			UnityEngine.Color arg0 = ToLua.ToColor(L, 2);
			obj.endValueColor = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index endValueColor on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_endValueString(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.endValueString = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index endValueString on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_endValueRect(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			UnityEngine.Rect arg0 = StackTraits<UnityEngine.Rect>.Check(L, 2);
			obj.endValueRect = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index endValueRect on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_endValueTransform(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
			obj.endValueTransform = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index endValueTransform on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_optionalBool0(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.optionalBool0 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index optionalBool0 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_optionalFloat0(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.optionalFloat0 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index optionalFloat0 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_optionalInt0(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.optionalInt0 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index optionalInt0 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_optionalRotationMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			DG.Tweening.RotateMode arg0 = (DG.Tweening.RotateMode)ToLua.CheckObject(L, 2, typeof(DG.Tweening.RotateMode));
			obj.optionalRotationMode = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index optionalRotationMode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_optionalScrambleMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			DG.Tweening.ScrambleMode arg0 = (DG.Tweening.ScrambleMode)ToLua.CheckObject(L, 2, typeof(DG.Tweening.ScrambleMode));
			obj.optionalScrambleMode = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index optionalScrambleMode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_optionalString(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.DOTweenAnimation obj = (DG.Tweening.DOTweenAnimation)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.optionalString = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index optionalString on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnReset(IntPtr L)
	{
		try
		{
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'DG.Tweening.DOTweenAnimation.OnReset' can only appear on the left hand side of += or -= when used outside of the type 'DG.Tweening.DOTweenAnimation'");
			}

			if (arg0.op == EventOp.Add)
			{
				System.Action<DG.Tweening.DOTweenAnimation> ev = (System.Action<DG.Tweening.DOTweenAnimation>)arg0.func;
				DG.Tweening.DOTweenAnimation.OnReset += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				System.Action<DG.Tweening.DOTweenAnimation> ev = (System.Action<DG.Tweening.DOTweenAnimation>)arg0.func;
				DG.Tweening.DOTweenAnimation.OnReset -= ev;
			}

			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

