---@class DG.Tweening.Ease : System.Enum
---@field value__ int
---@field Unset DG.Tweening.Ease
---@field Linear DG.Tweening.Ease
---@field InSine DG.Tweening.Ease
---@field OutSine DG.Tweening.Ease
---@field InOutSine DG.Tweening.Ease
---@field InQuad DG.Tweening.Ease
---@field OutQuad DG.Tweening.Ease
---@field InOutQuad DG.Tweening.Ease
---@field InCubic DG.Tweening.Ease
---@field OutCubic DG.Tweening.Ease
---@field InOutCubic DG.Tweening.Ease
---@field InQuart DG.Tweening.Ease
---@field OutQuart DG.Tweening.Ease
---@field InOutQuart DG.Tweening.Ease
---@field InQuint DG.Tweening.Ease
---@field OutQuint DG.Tweening.Ease
---@field InOutQuint DG.Tweening.Ease
---@field InExpo DG.Tweening.Ease
---@field OutExpo DG.Tweening.Ease
---@field InOutExpo DG.Tweening.Ease
---@field InCirc DG.Tweening.Ease
---@field OutCirc DG.Tweening.Ease
---@field InOutCirc DG.Tweening.Ease
---@field InElastic DG.Tweening.Ease
---@field OutElastic DG.Tweening.Ease
---@field InOutElastic DG.Tweening.Ease
---@field InBack DG.Tweening.Ease
---@field OutBack DG.Tweening.Ease
---@field InOutBack DG.Tweening.Ease
---@field InBounce DG.Tweening.Ease
---@field OutBounce DG.Tweening.Ease
---@field InOutBounce DG.Tweening.Ease
---@field Flash DG.Tweening.Ease
---@field InFlash DG.Tweening.Ease
---@field OutFlash DG.Tweening.Ease
---@field InOutFlash DG.Tweening.Ease
---@field INTERNAL_Zero DG.Tweening.Ease
---@field INTERNAL_Custom DG.Tweening.Ease
local m = {}
DG = {}
DG.Tweening = {}
DG.Tweening.Ease = m
return m